// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAYGxtoe3uvDRLdAUJXYMPa2BEKQywUhQ',
    appId: '1:424769384934:web:66f0a40f7a4962f9c26627',
    messagingSenderId: '424769384934',
    projectId: 'csen268-s25-g4-9396e',
    authDomain: 'csen268-s25-g4-9396e.firebaseapp.com',
    storageBucket: 'csen268-s25-g4-9396e.firebasestorage.app',
    measurementId: 'G-GGYYSELQ6X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ9If1PNWPAlcV4Eaa4jEIhO5DZj1Hbx8',
    appId: '1:424769384934:android:e59b25a2dbff7b2ac26627',
    messagingSenderId: '424769384934',
    projectId: 'csen268-s25-g4-9396e',
    storageBucket: 'csen268-s25-g4-9396e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfhB21iPBm_0C3CP4MyAX2DusYtobz2zk',
    appId: '1:424769384934:ios:5401c869a0115ccac26627',
    messagingSenderId: '424769384934',
    projectId: 'csen268-s25-g4-9396e',
    storageBucket: 'csen268-s25-g4-9396e.firebasestorage.app',
    iosBundleId: 'com.csen268.s25.g4',
  );
}
